#!/bin/bash
#
# Capabilities get lost when creating the fai base.tar.xz image.
# Restore them here.
#

set -e

if [ ! -x $target/sbin/setcap ] ; then
    exit 0
fi

for FILE in /bin/ping /usr/bin/fping ; do
    if [ -x $target/$FILE ] ; then
        $ROOTCMD /sbin/setcap cap_net_raw+ep $FILE && chmod -s $target/$FILE
    fi
done
if [ -x $target/usr/bin/systemd-detect-virt ] ; then
    $ROOTCMD /sbin/setcap cap_dac_override,cap_sys_ptrace+ep /usr/bin/systemd-detect-virt
fi

# We don't use IPv6
for FILE in /bin/ping6 /usr/bin/fping6; do
	rm -f $target/$FILE
done
