#! /bin/bash

# Echo architecture and OS name in uppercase. Do NOT remove these two lines.
uname -s | tr '[:lower:]' '[:upper:]'
[ -x "`which dpkg`" ] && dpkg --print-architecture | tr a-z A-Z

# XXX: FAI 4 deprecated FAICD class but we use it
[ -d /media/mirror ] && echo "FAICD"

exit 0
